# Generated by Django 2.2 on 2020-06-23 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_idea_feed', '0001_initial'),
        ('app_user_actions', '0003_auto_20200623_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('idea_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_idea', to='app_idea_feed.IdeaFeedItem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
