# Generated by Django 2.2 on 2020-06-15 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('theme', models.CharField(default='Data Science', max_length=25)),
                ('department', models.CharField(default='Finance', max_length=25)),
                ('rag_status', models.CharField(default='Green', max_length=15)),
                ('tags', models.CharField(default='#Innovation', max_length=150)),
                ('stage', models.CharField(default='Idea Initiation', max_length=20)),
                ('contributor', models.CharField(default='MentorA', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
