# Generated by Django 2.2 on 2020-06-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_actions', '0002_userfavouriteideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouriteideas',
            name='idea_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user', to='app_idea_feed.IdeaFeedItem'),
        ),
        migrations.AlterField(
            model_name='userfavouriteideas',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlikedideas',
            name='idea_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_idea', to='app_idea_feed.IdeaFeedItem'),
        ),
        migrations.AlterField(
            model_name='userlikedideas',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
