# Generated by Django 2.2 on 2020-06-23 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_idea_feed', '0001_initial'),
        ('app_user_actions', '0004_usercommentideas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavouriteideas',
            unique_together={('user_profile', 'idea_feed')},
        ),
        migrations.AlterUniqueTogether(
            name='userlikedideas',
            unique_together={('user_profile', 'idea_feed')},
        ),
    ]
